### PR TITLE
Mark SysVMQ as write barrier protected

### PR DESCRIPTION
**Pull request by casperisfine**
Since it has no references, there's nothing to do.

While I was at it I cleaned up the rb_data_type_t a bit via requiring Ruby 2.5+, which also allowed to remove a bunch of ifdefs.

This PR also migrate the repo to GitHub Actions and fix various test issues (e.g. minitest need to be declared as dependency etc).

### CODE REVIEW

**Comment by sirupsen** [comment]
Hey Jean [image: ❤]️[image: ❤]️[image: ❤]️ I’m travelling with too
terrible of a connection to merge and cut a release right now. I’ll do it
as soon as I’m better connected and make you a collaborator too

Simon
https://sirupsen.com/

**Comment by casperisfine** [comment]
No worries, no rush at all.

**Comment by sirupsen** [comment]
Released as 0.2.3 and added you as a collaborator 
CleanShot 2023-03-11 at 18 22 07@2x

**Comment by casperisfine** [comment]
❤️

**Pull request merged**
