### PR TITLE
Fix typo in sysvmq.c

### PR DESCRIPTION
**Pull request by kirs**
@sirupsen

### CODE REVIEW

**Comment by kirs** [comment]
Seems like CI for 1.9.3 is broken. Should we drop support for it?

**Comment by sirupsen** [comment]
Yeah, let's do it. Want to update this PR?

**Comment by sirupsen** [comment]
How did you run into this out of curiosity?

**Comment by kirs** [comment]
> How did you run into this out of curiosity?

Haha, I wanted to add "don't ask me how I found this" to the PR description :grimacing:

We're using SysVMQ for a project at Shopify and I've been dealing with `Failed receiving message from queue` error. I've decided to check the sources of sysvmq binding and grepped the error messages.

**Comment by sirupsen** [comment]
Is there any other information in that error message that would've helped you debug? Should we add that?

**Comment by kirs** [comment]
It's not directly related, but I faced some this weird behaviour on macOS:

```ruby
def test_sysv
  key = 0xDEADC0DE
  mq = SysVMQ.new(key, 1024, SysVMQ::IPC_CREAT | 0666)
  # works
  mq.send(' '.bytes * 256)
  # will crash with 'Size of message is bigger than buffer size'
  mq.send(' '.bytes * 257)
ensure
  mq.destroy
end
```

Even that the buffer size is `1024`, it doesn't allow messages < 256 bytes.

**Pull request merged**
